#!/bin/sh

case "$1" in
  start)
    echo "Starting aesdserver"
    start-stop-daemon --start --name aesdserver --exec /usr/bin/aesdserver -- -d
    ;;
  stop)
    echo "Stopping aesdserver"
    start-stop-daemon --stop --name aesdserver
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0